# Generated by Django 5.0.6 on 2024-07-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogLibros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='autor',
            name='email',
        ),
    ]
