# Generated by Django 3.2 on 2024-08-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogLibros', '0003_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
